import argparse
import matplotlib.pyplot as plt
import os
import numpy as np

def plot_cdf(log, save_dir, log_scale):
    packet_count = []

    # Read the log file and find the total packet count
    with open(log, 'r') as f:
        lines = f.readlines()

    # Find the starting point for flow analysis and total packet count
    for line in lines:
        if line.startswith("All Flows by Packet Count:"):
            break
    
    # Process each flow and its packet count
    for line in lines[lines.index(line) + 1:]:
        if line.strip():
            parts = line.split('->')
            count = int(parts[1].strip().split(': ')[1])
            packet_count.append(count)

    # Sort packet counts in ascending order
    packet_count = np.array(packet_count)[::-1]

    # Compute the CDF based on the number of flows
    total_flows = len(packet_count)
    cdf_values = np.arange(1, total_flows + 1) / total_flows

    # Plot the CDF
    plt.figure(figsize=(10, 6))
    plt.plot(packet_count, cdf_values, linestyle='-', color='blue', linewidth=2)  # Smooth curve with no markers

    # Set x-axis to logarithmic scale if specified
    if log_scale:
        plt.xscale('log')
        plt.xlabel('Packet Count (Log Scale)')
    else:
        plt.xlabel('Packet Count')

    plt.ylabel('CDF')
    plt.title('Cumulative Distribution Function (CDF) of Packet Counts')
    plt.ylim(0, 1)  # Set y-axis range from 0 to 1
    plt.grid(True)

    # Save the plot file, append a suffix based on log_scale
    base_name = os.path.splitext(os.path.basename(log))[0]
    log_suffix = '_log' if log_scale else ''
    save_name = f'{base_name}_cdf_packet_counts{log_suffix}.png'

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    plt.savefig(os.path.join(save_dir, save_name))
    plt.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Generate CDF plot from flow analysis log.')
    parser.add_argument('--log', type=str, required=True, help='Path to the log file generated by the analysis script.')
    parser.add_argument('--log_scale', action='store_true', help='Use logarithmic scale for the x-axis (packet count).')
    parser.add_argument('--save', type=str, required=True, help='Directory to save the output plot.')

    args = parser.parse_args()

    # Call the CDF plot function with the provided arguments
    plot_cdf(args.log, args.save, args.log_scale)
